//
//  RecipeData.swift
//  mcChesneyK_GroceryList_v3.0
//
//  Created by Kristina McChesney on 3/15/20.
//  Copyright © 2020 Kristina McChesney. All rights reserved.
//
//  All recipes and photos are from hellofresh.com
//

import Foundation

// create a list of recipe objects
let recipes =
[Recipe("Salmon Limone",
        "2 unit Scallions\n½ cup Israeli Couscous\n10 ounce Salmon\n1 unit Zucchini\n1 unit Roma Tomato\n1 unit Chicken Stock Concentrate\n1 teaspoon Italian Seasoning\n1 unit Lemon\n2 tablespoon Sour Cream\n2 tablespoon Butter\n5 teaspoon Olive Oil",
        "Wash and dry all produce. Trim and thinly slice scallions, separating whites from greens. Dice tomato.\n\nMelt 1 TBSP butter (2 TBSP for 4 servings) in a medium pot over mediumhigh heat. Add couscous and cook, stirring occasionally, until lightly toasted, 2-3 minutes. Pour in ¾ cup water (1½ cups for 4) and stock concentrate. Bring to a boil, then cover and reduce to a low simmer. Cook until couscous is al dente, 6-8 minutes. Pour out any excess liquid, if necessary. Cover pot and set aside.\n\nRinse salmon, then pat dry with paper towels. Season all over with salt, pepper, and Italian Seasoning. Heat 1 TBSP butter and 1 TBSP olive oil in a large, preferably nonstick, pan over medium-high heat. Add salmon skin sides down and cook until skin is browned and crispy, 3-4 minutes. Flip and cook until fish is opaque and cooked through, 3-4 minutes more. Transfer to a paper-towel-lined plate.\n\nMeanwhile, using a peeler, shave zucchini lengthwise into ribbons, rotating as you go, until you get to the seedy core; discard core. Zest and halve lemon; cut one half into 2 wedges (for 4 servings, halve one lemon and quarter other). In a medium bowl, combine scallion greens, tomato, and zucchini ribbons. Add a large drizzle of olive oil and juice from lemon half (two halves for 4). Season with salt and pepper and toss to combine.\n\nReserve ¼ tsp lemon zest (½ tsp for 4 servings). Fluff couscous with a fork; stir in scallion whites and remaining lemon zest. Season with salt and pepper. In a small bowl, combine sour cream, reserved lemon zest, salt, and pepper. Add water 1 tsp at a time until mixture reaches a drizzling consistency.\n\nDivide couscous between bowls or plates; top with salmon and salad. Drizzle crema over everything. Serve with lemon wedges on the side." ),
 Recipe("Poblano Mac & Cheese",
        "1 unit Poblano Pepper\n2 clove Garlic\n½ cup Panko Breadcrumbs\n8 ounce Cream Sauce Base\n½ cup Pepper Jack Cheese\n½ cup Mexican Cheese Blend\n1 unit Roma Tomato\n6 ounce Cavatappi Pasta\n1 tablespoon Southwest Spice Blend\n2 tablespoon Cream Cheese\n¼ cup Monterey Jack Cheese\n2 teaspoon Olive Oil\n1 tablespoon Butter",
        "Adjust rack to top position and preheat oven to 425 degrees. Bring a medium pot of salted water to a boil (use a large pot for 4 servings). Wash and dry all produce. Halve poblano lengthwise; remove stem and seeds. Dice tomato. Place garlic cloves on a small piece of foil; drizzle with olive oil and season with salt and pepper. Cinch into a packet.\n\nPlace poblano halves cut sides down on a baking sheet. Drizzle with olive oil; season with salt and pepper. Place garlic foil packet on same sheet. Roast on top rack until poblano is tender and lightly blistered and garlic is softened, 15-17 minutes. Remove from oven. Once cool enough to handle, transfer everything to a cutting board. Dice poblano. Mash garlic with a fork. Heat broiler to high or oven to 500 degrees.\n\nOnce water is boiling, add cavatappi to pot. Cook until al dente, 9-11 minutes. Reserve ¾ cup pasta cooking water, then drain. Meanwhile, place 1 TBSP butter (2 TBSP for 4 servings) in a small bowl; microwave until melted, 30 seconds. Stir in panko and half the Southwest Spice (you’ll use the rest later). Season with salt and pepper.\n\nHeat pot used for cavatappi over medium heat. Cut top off carton of cream sauce base to open fully; pour contents into pot. Using a spoon or spatula, scrape any remaining sauce from carton into pot. Add cream cheese and remaining Southwest Spice; bring to a simmer, whisking, until smooth, 1-2 minutes. Reduce heat to low and whisk in pepper jack, Monterey Jack, and Mexican cheese until melted and smooth.\n\nStir cavatappi, mashed garlic, diced poblano, and tomato into pot with cheese sauce. If needed, stir in reserved pasta cooking water a splash at a time until cavatappi is coated in a creamy sauce. Season with salt and pepper.\n\nTransfer mac & cheese to an 8-by- 8-inch baking dish (for 4 servings, use a 9-by-13-inch baking dish). Sprinkle with seasoned panko; broil or bake on top rack until panko is browned and crispy, 2-3 minutes. Divide between plates or serve directly from dish."),
 Recipe("Bulgogi Pork Tenderloin",
        "12 ounce Carrots\n2 unit Scallions\n12 ounce Pork Tenderloin\n1 tablespoon Sesame Seeds\n1 unit Lime\n½ cup Jasmine Rice\n4 ounce Bulgogi Sauce\n1 teaspoon Olive Oil\n1 teaspoon Vegetable Oil\n2 tablespoon Butter",
        "Adjust rack to top position (top and middle positions for 4 servings) and preheat oven to 425 degrees. Wash and dry all produce. Trim, peel, and cut carrots into ½-inch-thick pieces. Zest and quarter lime. Thinly slice scallions, separating whites from greens.\n\nIn a small pot, combine rice, ¾ cup water (1½ cups for 4 servings), and a big pinch of salt. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to serve.\n\nWhile rice cooks, toss carrots on one side of a baking sheet with a drizzle of olive oil, salt, and pepper. (For 4 servings, spread out across whole sheet.) Roast on top rack for 10 minutes (we’ll add the pork then).\n\nMeanwhile, pat pork dry with paper towels; season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium heat. Add pork; sear, turning occasionally, until browned all over, 4-8 minutes. Once carrots have roasted 10 minutes, remove sheet from oven. Flip carrots and place seared pork on empty side. (For 4 servings, add pork to a second sheet; roast on middle rack.) Roast until pork is cooked through and carrots are tender, 10-12 minutes more. TIP: If carrots are done before pork, remove from sheet and continue roasting pork.\n\nWhen pork and carrots have 5 minutes left in the oven, melt 1 TBSP butter in pan used for pork over medium-high heat. Add scallion whites and cook until fragrant, 1-2 minutes. Stir in bulgogi sauce and 1 TBSP water. Bring to a simmer, stirring, until warmed through, 2-3 minutes. Turn off heat. TIP: If sauce is too thick, stir in a splash of water.\n\nFluff rice with a fork. Stir in 1 TBSP butter, a squeeze of lime juice, and half the lime zest (add more zest if you like). Season with salt and pepper. Thinly slice pork crosswise. Divide rice, pork, and carrots between plates. Drizzle pork with sauce. Sprinkle with scallion greens and sesame seeds. Serve with remaining lime wedges on the side."),
 Recipe("Coconut Tempura Shrimp",
        "¾ cup Jasmine Rice\n1 unit Lime\n4 ounce Shredded Red Cabbage\n2 tablespoon Mayonnaise\n2 teaspoon Sriracha\n10 ounce Shrimp\n¼ ounce Cilantro\n4 ounce Pineapple\n½ ounce Cashews\n6 tablespoon Apricot Jam\n¼ cup Shredded Coconut\n82 g Tempura Mix\n1 teaspoon Sugar\n1 tablespoon Butter\n1 teaspoon Vegetable Oil",
        "In a medium pot, combine rice, 1¼ cups water (2¼ cups for 4 servings), and a pinch of salt. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to serve.\n\nMeanwhile, wash and dry all produce. Roughly chop cilantro. Zest and halve lime (for 4 servings, zest 1 lime; halve both). Drain pineapple over a small bowl, reserving juice. In a medium bowl, toss together cabbage, cilantro, pineapple, mayonnaise, juice from half the lime, half the pineapple juice, and ½ tsp sugar (1 tsp for 4). Season with salt and pepper. Add cashews.\n\nTo bowl with reserved pineapple juice, stir in jam, a squeeze of lime juice, and sriracha to taste. Set aside. Heat a large, heavy-bottomed pan (preferably nonstick) over medium heat. Add coconut and ½ tsp sugar (1 tsp for 4 servings); cook, stirring occasionally, until lightly browned, 1-2 minutes. Turn off heat; transfer to a second small bowl. Wipe out pan.\n\nRinse shrimp under cold water, then pat very dry with paper towels. Season with salt. In a large bowl, combine tempura mix, half the toasted coconut, ½ tsp salt (1 tsp for 4 servings), and ⅓ cup cold water (⅔ cup for 4). (TIP: If mixture is too thick, add more water 1 TBSP at a time until it reaches a pancake-batter-like consistency.) Heat a ¼-inch layer of oil in pan used for coconut over medium-high heat. Stir shrimp into batter until fully coated. Line a plate with paper towels.\n\nOnce oil is hot enough that a drop of batter sizzles when added to the pan, add coated shrimp in a single layer. Cook in batches until golden brown and cooked through, 2-3 minutes on the first side and 1-2 minutes on the second side. (TIP: Add more oil as needed between batches, allowing it time to heat back up before frying more shrimp.) Using a slotted spoon, transfer shrimp to papertowel- lined plate. Immediately season with salt and pepper.\n\nFluff rice with a fork and stir in 1 TBSP butter (2 TBSP for 4 servings) and lime zest to taste; season with salt. Divide rice, shrimp, and tropical slaw between plates. Sprinkle shrimp and rice with remaining toasted coconut. Drizzle shrimp with sauce (or serve on the side for dipping)."),
 Recipe("Pulled Pork Bowl",
        "½ cup Jasmine Rice\n1 unit Green Bell Pepper\n¼ ounce Cilantro\n10 ounce Pulled Pork\n1 unit Chicken Stock Concentrate\n4 tablespoon Sour Cream\n1 unit Red Onion\n1 unit Roma Tomato\n1 unit Lime\n1 tablespoon Fajita Spice Blend\n¼ cup Monterey Jack Cheese\n2 tablespoon Butter\n4 teaspoon Vegetable Oil",
        "In a small pot, combine ¾ cup water and 1 TBSP butter. (For 4 servings, combine 1½ cups water and 2 TBSP butter.) Bring to a boil, then stir in rice. Cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to serve.\n\nMeanwhile, wash and dry all produce. Halve, peel, and thinly slice onion; mince a few slices until you have 2 TBSP (3 TBSP for 4 servings). Halve, core, and thinly slice bell pepper into strips. Dice tomato. Finely chop cilantro. Quarter lime.\n\nHeat a large drizzle of oil in a large pan over medium-high heat. Add sliced onion and bell pepper. Cook, stirring, until just softened, 3-4 minutes.\n\nTear pulled pork into smaller pieces. Add to pan with veggies along with another large drizzle of oil. Season with salt, pepper, and Fajita Spice. Cook, stirring, until pork is warmed through, 2-3 minutes. Stir in stock concentrate and ½ cup water (¾ cup for 4 servings). Bring to a boil, then reduce heat to low and stir in 1 TBSP butter (2 TBSP for 4). Let simmer until saucy, 1-2 minutes.\n\nWhile pork simmers, in a small bowl, combine tomato, minced onion, half the cilantro, juice from half the lime, salt, and pepper.\n\nFluff rice with a fork; season with salt and pepper. Divide between plates. Top with pork mixture, salsa, and Monterey Jack. Dollop with sour cream and sprinkle with remaining cilantro. Serve with remaining lime wedges on the side."),
 Recipe("Chicken Breasts",
        "8 ounce Brussels Sprouts\n1 unit Shallot\n4 ounce Bacon\n12 ounce Chicken Breasts\n1 unit Chicken Demi-Glace\n1 teaspoon Chili Flakes\n2 unit Scallions\n12 ounce Yukon Gold Potatoes\n2 tablespoon Brown Sugar\n2 tablespoon Garlic Herb Butter\n6 tablespoon Sour Cream\n1 tablespoon Butter\n1 tablespoon Vegetable Oil",
        "Place a foil-lined baking sheet on top rack (2 sheets, on top and middle racks, for 4 servings); preheat oven to 425 degrees. Wash and dry all produce. Trim and halve Brussels sprouts. Trim and thinly slice scallions, separating whites from greens. Halve, peel, and mince shallot until you have 3 TBSP.\n\nDice potatoes into ½-inch pieces; place in a large pot with enough salted water to cover by 2 inches. Bring to a boil and cook until tender, 15-20 minutes. Reserve ½ cup potato cooking liquid; drain. Melt 1 TBSP plain butter in empty pot over medium heat. Add scallion whites; cook until softened, 1 minute. Return potatoes to pot; mash until smooth. Season with salt and pepper. Turn off heat; keep covered until ready to serve.\n\nMeanwhile, carefully toss Brussels sprouts on one side of prepared baking sheet with a drizzle of oil, salt, and pepper; arrange cut sides down. Add bacon to empty side; season with salt and pepper. (For 4, divide between 2 sheets; roast Brussels sprouts on top rack and bacon on middle rack.) Roast 10 minutes, then remove from oven. Sprinkle bacon with brown sugar. Return to oven until bacon is crispy and Brussels sprouts are tender, 10-15 minutes more.\n\nMeanwhile, pat chicken dry with paper towels; season all over with salt and pepper. Heat a large drizzle of oil in a large pan over medium-high heat. Add chicken and cook until browned and cooked through, 5-8 minutes per side. During the last 2 minutes of cooking, reduce heat to low and add garlic herb butter. Spoon over chicken until coated. Turn off heat. Leaving butter in pan, transfer chicken to a cutting board.\n\nAdd minced shallot to pan with reserved garlic herb butter. Cook over low heat until softened, 1-2 minutes. Stir in demi-glace, any resting juices from chicken, and ¼ cup water. Simmer until slightly thickened, 1-2 minutes. Turn off heat. Stir in 2 packets sour cream (4 packets for 4 servings; you’ll use the rest later). Season with salt and pepper.\n\nSlice chicken crosswise. Chop bacon into small pieces. Stir remaining sour cream into potatoes; add splashes of reserved potato cooking liquid as needed until creamy. Divide potatoes and Brussels sprouts between plates. Top potatoes with chicken and sauce. Garnish chicken with scallion greens and Brussels sprouts with bacon. Sprinkle with chili flakes to taste."),
 Recipe("Beef Tenderloin",
        "2 unit Sweet Potato\n6 ounce Asparagus\n10 ounce Beef Tenderloin\n½ ounce Sliced Almonds\n¼ ounce Chives\n1 tablespoon Tricolored Peppercorns\n1 unit Beef Stock Concentrate\n2 tablespoon Sour Cream\n2 teaspoon Vegetable Oil\n3 tablespoon Butter",
        "Bring 3 TBSP butter (6 TBSP for 4 servings) to room temperature. Wash and dry all produce. Peel and dice sweet potatoes into ½-inch pieces. Place in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until tender, 15-20 minutes. Drain and return sweet potatoes to pot.\n\nMeanwhile, thinly slice chives. Trim and discard woody bottom ends from asparagus. Put peppercorns in a zip-close bag and crush with a heavy-bottomed pan or rolling pin; pour onto a plate and spread into an even layer. Pat beef dry with paper towels; season all over with salt. Press both sides of beef into peppercorns to evenly coat. TIP: For a milder flavor, sprinkle beef with peppercorns instead.\n\nHeat a drizzle of oil in a large pan over medium-high heat. Add beef and cook almost to desired doneness, 4-7 minutes per side. Add stock concentrate and 2 TBSP water (3 TBSP for 4 servings). Simmer until sauce has thickened and beef reaches desired doneness, 1-2 minutes. Turn beef to coat, then transfer to a shallow dish. Turn off heat; wipe out pan.\n\nHeat a drizzle of oil in same pan over medium-high heat. Add asparagus; season with salt and pepper. Cook, stirring, until lightly browned and tender, 3-5 minutes. Transfer to a plate. Add almonds to same pan; cook, stirring, until lightly toasted, 30-60 seconds. Season with salt and pepper. Transfer to a small bowl.\n\nMash sweet potatoes until smooth. (TIP: If potatoes have cooled, mash over medium-low heat.) Stir in sour cream and 1 TBSP softened butter (2 TBSP for 4 servings) until combined. Season generously with salt and pepper.\n\nIn a second small bowl, combine remaining 2 TBSP softened butter (4 TBSP for 4 servings), 1 tsp chives (2 tsp for 4), salt, and pepper. (TIP: If butter is still cold, microwave 5-10 seconds.) Divide beef, sweet potatoes, and asparagus between plates. Sprinkle asparagus with almonds. Top beef with chive butter. Garnish with remaining chives and serve."),
 Recipe("Noodle Soup",
        "3 ounce Carrot\n1 unit Roma Tomato\n1 tablespoon Italian Seasoning\n2 unit Chicken Stock Concentrate\n¼ cup Parmesan Cheese\n1 unit Ciabatta Bread\n1 unit Yellow Onion\n9 ounce Italian Chicken Sausage Mix\n1 teaspoon Garlic Powder\n6 ounce Farfalle Pasta\n1 teaspoon Chili Flakes\n5 ounce Spinach\n2 teaspoon Olive Oil\n2 tablespoon Butter",
        "Wash and dry all produce. Trim, peel, and cut carrot into a small dice. Halve, peel, and finely chop onion. Dice tomato.\n\nHeat a drizzle of olive oil in a large pot over medium-high heat. Add sausage and cook, breaking up meat into pieces, until browned, 4-6 minutes (it’ll finish cooking in the next step).\n\nAdd another drizzle of olive oil to pot with sausage, then stir in carrot, onion, and a large pinch of salt. Cook, stirring occasionally, until veggies are just softened and sausage is cooked through, 5-7 minutes.\n\nAdd tomato, half the Italian Seasoning (use the rest as you like), and ¼ tsp garlic powder (½ tsp for 4 servings; you’ll use more later) to pot. Cook, stirring, until fragrant, 1 minute. Stir in stock concentrates and 3½ cups warm water (6 cups for 4), scraping up any browned bits from bottom of pot. Add half the farfalle (all for 4). Cover and bring to a boil, then immediately reduce heat to low. Simmer until pasta is al dente, 10 minutes.\n\nMeanwhile, place 2 TBSP butter (3 TBSP for 4 servings) in a small microwave-safe bowl; microwave until just softened, 10 seconds (do not melt). Stir in 1 TBSP Parmesan (2 TBSP for 4; you’ll use the rest later), ¼ tsp garlic powder (use remaining garlic powder for 4), and a pinch of salt and chili flakes to taste. Halve ciabatta and toast until golden. Spread butter mixture onto cut sides of ciabatta, then halve on a diagonal.\n\nStir spinach and 2 TBSP Parmesan (4 TBSP for 4 servings) into soup until spinach is wilted. Season with plenty of salt and pepper. Divide soup between bowls; sprinkle with remaining Parmesan and a pinch of chili flakes if desired. Serve with toasts on the side for dipping."),
 Recipe("Grilled Cheese",
        "1 unit Zucchini\n1 unit Lemon\n¼ ounce Cilantro\n1 unit Vegetable Stock Concentrate\n8 ounce Grilling Cheese\n1 unit Red Onion\n4 ounce Grape Tomatoes\n½ cup Israeli Couscous\n1 teaspoon Sumac\n1 tablespoon Za'atar Spice Blend\n4 teaspoon Olive Oil",
        "Adjust rack to top position and heat broiler to high or oven to 500 degrees. Wash and dry all produce. Halve zucchini lengthwise; cut into long, thin wedges. Halve, peel, and cut onion into 1-inch-thick wedges; mince 1 wedge. Zest and quarter lemon. Halve tomatoes. Roughly chop cilantro leaves and stems.\n\nHeat a drizzle of olive oil in a small pot over medium-high heat. Add minced onion and couscous. Cook, stirring, until onion is softened and couscous is lightly toasted, 2-3 minutes. Add ¾ cup water (1½ cups for 4 servings) and stock concentrate. Bring to a boil, then cover and reduce to a low simmer. Cook until couscous is tender, 6-8 minutes. Keep covered off heat.\n\nMeanwhile, toss zucchini and onion wedges on a baking sheet with a large drizzle of olive oil, sumac, salt, and pepper. Broil or bake on top rack, tossing halfway through, until lightly charred, 10-15 minutes.\n\nWhile veggies roast, slice grilling cheese into four large pieces (for 4 servings, cut into eight large pieces). Place Za’atar Spice on a plate. Coat cheese in za’atar, pressing to adhere. Heat a drizzle of olive oil in a large, preferably nonstick, pan over mediumhigh heat. Add cheese and cook until browned, 1-2 minutes per side.\n\nTransfer cooked couscous to a large bowl. Stir in tomatoes, lemon zest, half the roasted veggies, half the cilantro, and a squeeze of lemon juice. Season with salt and pepper.\n\nDivide couscous mixture between plates. Top with grilling cheese and remaining roasted veggies. Garnish with remaining cilantro. Serve with remaining lemon wedges on the side."),
 Recipe("Chicken Tacos",
        "1 unit Red Onion\n1 teaspoon Sriracha\n4 ounce Shredded Red Cabbage\n8 tablespoon Teriyaki Sauce\n6 unit Flour Tortillas\n5 teaspoon Red Wine Vinegar\n2 tablespoon Sour Cream\n10 ounce Chicken Breast Strips\n1 tablespoon Sesame Seeds\n1 teaspoon Sugar\n1 tablespoon Vegetable Oil",
        "Wash and dry produce. Halve, peel, and very thinly slice onion. In a small bowl, combine half the vinegar (you’ll use the rest later), ½ tsp sugar (1 tsp for 4 servings), and a pinch of salt and pepper. Add ¼ of the sliced onion; toss to coat. Set aside, stirring occasionally, until ready to serve.\n\nIn a medium bowl, combine sour cream, remaining vinegar, ½ tsp sugar (1 tsp for 4 servings), and sriracha (start with half and add more if you like things spicy). Stir in half the cabbage. Season with salt and pepper. Set aside, stirring occasionally, until ready to serve.\n\nHeat a large drizzle of oil in a large pan over medium-high heat. Add remaining onion and cabbage and season with salt and pepper. Cook, stirring, until slightly softened, 2-3 minutes.\n\nMeanwhile, pat chicken dry with paper towels. Add to pan with veggies along with another drizzle of oil, salt, and pepper. Cook, stirring often, until chicken is browned and cooked through, 4-6 minutes.\n\nAdd teriyaki sauce to pan; bring to a boil. Reduce to a low simmer and cook until sauce is slightly thickened and coats chicken and veggies, 4-6 minutes. Stir in half the sesame seeds. Season with salt and pepper.\n\nWrap tortillas in damp paper towels and microwave until warm and pliable, 30 seconds. Divide chicken and veggie mixture (using a slotted spoon if needed) between tortillas. Top with cabbage slaw and pickled onion. Sprinkle with remaining sesame seeds and serve."),
 Recipe("Lobster Ravioli & Shrimp",
        "1 unit Lemon\n10 ounce Shrimp\n9 ounce Lobster Ravioli\n2 tablespoon Sour Cream\n¼ ounce Dill\n1 unit Zucchini\n1 unit Vegetable Stock Concentrate\n4 teaspoon Olive Oil\n1 tablespoon Butter",
        "Bring a large pot of salted water to a simmer. Wash and dry all produce. Zest lemon; cut into wedges. Pick and roughly chop fronds from dill; discard stems. Rinse and pat shrimp dry with paper towels; season all over with salt and pepper.\n\nTrim ends from zucchini. Using a peeler, shave zucchini lengthwise into ribbons, rotating as you go, until you get to the seedy core. Discard core. Toss zucchini ribbons in a large bowl with half the lemon zest, juice from 1 lemon wedge (2 wedges for 4 servings), a large drizzle of olive oil, salt, and pepper.\n\nHeat a large drizzle of olive oil in a large, preferably nonstick, pan over medium-high heat. Add shrimp and cook, stirring, until opaque and cooked through, 3-4 minutes.\n\nWhile shrimp cooks, add ravioli to simmering water. Cook until tender and floating to the top, 3-4 minutes. Turn off heat, leaving ravioli in water.\n\nStir stock concentrate and ¼ cup water (⅓ cup for 4 servings) into pan with shrimp. Bring to a simmer over medium heat, then gently add ravioli using a slotted spoon. Reduce heat to low and stir in sour cream, 1 TBSP butter (2 TBSP for 4), half the dill, and a squeeze of lemon juice. Season with salt and pepper. TIP: If mixture seems dry, add a splash more water.\n\nDivide ravioli mixture between shallow bowls or plates. Top with zucchini ribbons. Garnish with remaining lemon zest and dill. Serve with remaining lemon wedges on the side."),
 Recipe("Pulled Chicken Rice",
        "½ cup Jasmine Rice\n1 unit Green Bell Pepper\n¼ ounce Cilantro\n8 ounce Pulled Chicken\n1 unit Chicken Stock Concentrate\n4 tablespoon Sour Cream\n1 unit Red Onion\n1 unit Roma Tomato\n1 unit Lime\n1 tablespoon Fajita Spice Blend\n¼ cup Monterey Jack Cheese\n4 teaspoon Vegetable Oil\n2 tablespoon Butter",
        "In a small pot, combine 1 cup water (1½ cups for 4 servings) and 1 TBSP butter (2 TBSP for 4). Bring to a boil, then stir in rice, cover, and reduce to a low simmer. Cook until rice is tender, 15- 18 minutes. Keep covered off heat until ready to serve.\n\nMeanwhile, wash and dry all produce. Halve, peel, and thinly slice onion; mince a few slices until you have 2 TBSP (3 TBSP for 4 servings). Core, deseed, and thinly slice bell pepper. Finely dice tomato. Finely chop cilantro leaves and stems. Quarter lime.Heat a large drizzle of oil in a large pan over medium-high heat. Add sliced onion and bell pepper. Cook, stirring, until just softened, 3-4 minutes.\n\nAdd another large drizzle of oil to pan with veggies. Break up chicken into smaller pieces and add to pan. Season with salt, pepper, and Fajita Spice. Cook, stirring, until warmed through, 2-3 minutes. Stir in stock concentrate and ½ cup water (¾ cup for 4 servings). Bring to a boil, then reduce to a low simmer and stir in 1 TBSP butter (2 TBSP for 4). Let simmer 1-2 minutes.\n\nMeanwhile, in a small bowl, combine tomato, minced onion, and half the cilantro. Add a squeeze of lime juice to taste and season with salt and pepper.\n\nFluff rice with a fork and season with salt and pepper. Divide between plates and top with chicken and veggie mixture. Garnish with Monterey Jack, salsa, sour cream, and remaining cilantro. Serve with remaining lime wedges on the side.")]

